services:
  backend:
    build: ./api
    ports:
      - "5080:5000"
    environment:
      - FLASK_ENV=production
      - DB_URI=sqlite:///db.sqlite3
      - SESSION_SECRET=valami_nagyon_titkos_es_veletlenszeru_nehezen_kitalalhato_1234
      - JWT_SECRET=valami_nagyon_titkos_es_veletlenszeru_csak_ne_ugyanaz_legyen_mint_a_SESSION_SECRET
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:5080
        VITE_BASE_URL: /
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
